In [ ]:
from nsepy import get_history
from datetime import date

data = get_history(symbol = 'INFY', start = date(2020,1,15), end = date(2021,1,15))
data[['Close']].plot()

In [11]:
infy = get_history(symbol = 'INFY', 
                    start = date(2020,1,15), 
                    end = date(2021,1,15))
infy

,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
Date,,,,,,,,,,,,,,
2020-01-15,INFY,EQ,775.65,773.85,773.85,762.15,766.30,767.55,766.99,6047430,4.638298e+14,96319,2874200,0.4753
2020-01-16,INFY,EQ,767.55,770.70,772.50,760.25,767.20,767.00,766.35,5740586,4.399309e+14,93520,2546218,0.4435
2020-01-17,INFY,EQ,767.00,770.70,772.90,762.25,767.45,767.85,766.35,3762957,2.883744e+14,98313,1716214,0.4561
2020-01-20,INFY,EQ,767.85,771.60,774.40,762.95,768.85,768.45,767.06,3887680,2.982075e+14,81096,1987288,0.5112
2020-01-21,INFY,EQ,768.45,768.45,770.50,760.75,761.15,762.50,764.09,4448374,3.398978e+14,83703,2831904,0.6366
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-11,INFY,EQ,1312.10,1342.10,1383.35,1340.00,1375.95,1376.20,1366.80,20528626,2.805855e+15,387124,6434782,0.3135
2021-01-12,INFY,EQ,1376.20,1378.00,1378.00,1360.00,1376.50,1371.75,1369.78,8309868,1.138271e+15,264378,3655022,0.4398
2021-01-13,INFY,EQ,1371.75,1373.85,1392.80,1360.00,1388.65,1387.15,1378.96,14442997,1.991624e+15,304458,6490234,0.4494
2021-01-14,INFY,EQ,1387.15,1360.00,1384.00,1318.45,1370.50,1370.50,1359.34,27521697,3.741122e+15,530803,10370390,0.3768
2021-01-15,INFY,EQ,1370.50,1360.00,1364.45,1340.00,1343.40,1344.95,1352.96,15018441,2.031942e+15,278300,8103557,0.5396

In [ ]:
infy.info()

In [ ]:
infy.describe()

In [18]:
# Stock futures (Similarly for index futures, set index = True)
stock_fut = get_history(symbol="INFY",
                            start = date(2021,1,16), 
                            end = date(2021,1,20),
                            futures=True,
                            expiry_date=date(2021,1,21))
stock_fut

Empty DataFrame
Columns: [Symbol, Expiry, Open, High, Low, Close, Last, Settle Price, Number of Contracts, Turnover, Open Interest, Change in OI, Underlying]
Index: []